name: Static Analysis

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop, feature/**]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    name: PHPStan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: curl

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress

  pint:
    runs-on: ubuntu-latest

    name: Pint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run Pint
        run: vendor/bin/pint --test
